### ISSUE TITLE
To make changes in connect plus 

### ISSUE THREAD

**Issue by jatinpandit66** [pembem22/connect-plus#60] opened 2022-09-01 17:27 UTC
Brother i highly request you to make changes in connect plus
Brother i bought new jbl xtreme 2 GG which are run on qcc chipset and my speaker firmware 2.7.0 which does not support LFM. Brother my main motive to buy this speaker to test LFM but i got the updated firmware speaker that doesn't support LFM.
Brother i tried your every version of connect plus
And firmware versions  for xtreme 2 qcc but nothing works 
Brother i highly request to make changes in App 
So that bin files are also supported because qcc files are bin files 
PLEASE HELP ME BROTHER I REALLY NEED YOU HELP PLEASE 🙏

**Comment by pembem22** [comment] 2022-09-01 19:47
Duplicate of #58.

Low frequency mode is not an official feature and is not guaranteed to work on any speaker. JBL can remove it from all the future speakers and there's nothing you can do about it. IMO, that's a right choice because the "low frequency" part of this mode is a side effect that can damage your speaker. Please do not rely on unofficial and undocumented features when considering buying a product.

**Closed by pembem22** 2022-09-01 19:47 UTC

**Comment by pembem22** [comment] 2022-09-01 19:48
Duplicate of #58.

**Comment by pembem22** [comment] 2022-09-01 19:48
Duplicate of #58

**Comment by jatinpandit66** [comment] 2022-09-02 00:30
But you can do some changes in your app to support qcc chipests 
It work with CSR chipset perfectly no doubt 
Brother i already know about LFM but i want it in anyway please

**Comment by jatinpandit66** [comment] 2022-09-02 00:31
Brother i can do anything for you but please help me to get LFM

**Comment by jatinpandit66** [comment] 2022-10-11 08:39
But you can do some changes in your app to support qcc chipests
It work with CSR chipset perfectly no doubt
Brother i already know about LFM but i want it in anyway please
