### ISSUE TITLE
Downgrading Compatibility

### ISSUE THREAD

**Issue by XboxOneSogie720** [pembem22/connect-plus#72] opened 2023-06-16 14:28 UTC
I tried using Android x86 to run this app and attempt to downgrade my XTREME 2, but the list of your firmware at your [firmware list](https://github.com/pembem22/jbl-firmware/tree/master/Xtreme%202%20QCC) repo are .bin and the app requires .dfu. Just renaming the file brings up an error after it seems to successfully upload the payload to the speaker.

Checking with the app confirms that mine's a QCC, but the QCC downloads, which are listed here, are only .bin.... Any idea what I could try?

**Comment by pembem22** [comment] 2023-06-16 19:10
Duplicate of #58

Flashing .bin files is not supported at the moment.

**Comment by pembem22** [comment] 2023-06-16 19:10
Duplicate of #58

**Closed by pembem22** 2023-06-16 19:10 UTC
