### ISSUE TITLE
It recognises speaker but doesn't connect (flip 5)

### ISSUE THREAD

**Issue by Krishna0501** [pembem22/connect-plus#74] opened 2023-07-18 17:05 UTC
![Screenshot_20230718_210148_ConnectPlus](https://github.com/pembem22/connect-plus/assets/90816725/c71602ab-0106-47bb-9d95-157f2965864e)

**Comment by AlexRow228** [comment] 2023-07-19 21:25
Same with my Xtreme 3,Pulse 4 and Boombox 3 dont even detect,please help
@pembem22

**Comment by XboxOneSogie720** [comment] 2023-07-19 21:28
@pembem22 The protocols for the newer speakers are apparently different. I can't remember if I read this as a comment in the code a while ago, or in an existing issue but that doesn't matter.

If that is true, then there is no simple fix on your end to make it work. The code would have to be appended to in the appropriate places to have support for the newer protocol.

**Comment by pembem22** [comment] 2023-07-28 20:30
Duplicate of #64

**Closed by pembem22** 2023-07-28 20:30 UTC
