### ISSUE TITLE
Hello Pembem22

### ISSUE THREAD

**Issue by Imantens** [pembem22/connect-plus#75] opened 2023-07-30 13:40 UTC
I like to downgrade my jbl xtreme 2 to 2.4.0.0
Now i have 2.7.0.0
And dont have LFM.

**Comment by Imantens** [comment] 2023-07-30 13:41
I got install app connect-plus and i dont have file to DFU to flash form QCC

**Comment by XboxOneSogie720** [comment] 2023-07-31 01:07
> I got install app connect-plus and i dont have file to DFU to flash form QCC

QCC models cannot be flashed. I was going to make an iOS version that supported QCC flashing, but I turned that down to focus on other iDevice hacking projects.

To download the firmware, see the README. To get a version of the app, go look at and download the previous commit from the one that removed QCC flashing.

**Comment by Imantens** [comment] 2023-07-31 10:29
Thx

**Comment by Tech-187** [comment] 2023-08-06 22:45
> > I got install app connect-plus and i dont have file to DFU to flash form QCC
> 
> QCC models cannot be flashed. I was going to make an iOS version that supported QCC flashing, but I turned that down to focus on other iDevice hacking projects.
> 
> To download the firmware, see the README. To get a version of the app, go look at and download the previous commit from the one that removed QCC flashing.

Ngl but you should make the app that supports QCC flashing as this became quite a problem and people have been looking for solutions for over 2 to maybe 3 years (since they forced the update to remove lfm I guess)

**Comment by XboxOneSogie720** [comment] 2023-08-06 22:47
@Tech-187 Do you have any Apple products? iPhone, Mac, iPad, or iPod?

**Comment by Tech-187** [comment] 2023-09-09 12:51
> @Tech-187 Do you have any Apple products? iPhone, Mac, iPad, or iPod?

lol I ignored this for a month because this looked like an Apple advertisement in the email but yes I do. I don't think it matters what platform you'd release it on regardless

**Comment by XboxOneSogie720** [comment] 2023-09-09 15:21
> > @Tech-187 Do you have any Apple products? iPhone, Mac, iPad, or iPod?
> 
> 
> 
> lol I ignored this for a month because this looked like an Apple advertisement in the email but yes I do. I don't think it matters what platform you'd release it on regardless

I know, but just in case I ever make a version of the app, you can try it.

**Comment by Tech-187** [comment] 2023-09-09 17:24
> > > @Tech-187 Do you have any Apple products? iPhone, Mac, iPad, or iPod?
> > 
> > 
> > lol I ignored this for a month because this looked like an Apple advertisement in the email but yes I do. I don't think it matters what platform you'd release it on regardless
> 
> I know, but just in case I ever make a version of the app, you can try it.

I should be able to try it out then lol

**Comment by pembem22** [comment] 2024-01-22 11:05
Duplicate of #58

**Closed by pembem22** 2024-01-22 11:05 UTC
