### ISSUE TITLE
can't connect to my boombox2

### ISSUE THREAD

**Issue by teapot2008** [pembem22/connect-plus#78] opened 2023-11-17 05:07 UTC
my system is miui 14,and it stay on this page
![Screenshot_2023-11-17-13-06-05-520_me andreww7985 connectplus](https://github.com/pembem22/connect-plus/assets/151073245/6388052e-009d-4eb0-b219-8ce14b228893)

**Comment by pembem22** [comment] 2024-01-01 22:41
Connecting to Boombox 2 is not supported at the moment.

**Comment by pembem22** [comment] 2024-01-01 22:41
Duplicate of #64

**Closed by pembem22** 2024-01-01 22:41 UTC
