### ISSUE TITLE
I have a QCC Xtreme2 GunMetal with the QCC5125 chip

### ISSUE THREAD

**Issue by SotirisSerJohn** [pembem22/connect-plus#63] opened 2022-11-27 13:09 UTC
I can give you the official blueflash and all the Qualcomm official files but, I need a dfu version of the v.8.8.8 file so I can flash it. Please make it happen
![16695544204892857346230136234921](https://user-images.githubusercontent.com/118826930/204136868-c1a8a49f-0cc8-41c2-9854-115c0f7109b5.jpg)
If you can't make a dfu file I at least need help with flashing it through PSTool. When I put it on dfu mode (play+ volume-) at first it recognised it as Qualcomm control module but nothing else happened. I can't re-enter dfu mode btw
![16695545005108937807235671910989](https://user-images.githubusercontent.com/118826930/204136911-1e526915-be6d-4f09-aa8a-f01642487645.jpg)

**Comment by Cretster** [comment] 2022-11-30 21:25
Are you also trying to flash yours to an older version?
I just bought a new Gunmetal Xtreme2 from Currys a week or two back and one of the first things I remembered was that my old Flip had the same LF mode and I thought this would do it too, only to find it's a removed function.  Damn shame.

I've tried with Connect Plus and it's a really cool app, but for some reason it doesn't seem to show the chipset even for mine to be able to confirm the type?  
Really wish I could downgrade it to an older FW though if you end up figuring it out.

**Comment by SotirisSerJohn** [comment] 2022-12-01 05:56
> Are you also trying to flash yours to an older version? I just bought a new Gunmetal Xtreme2 from Currys a week or two back and one of the first things I remembered was that my old Flip had the same LF mode and I thought this would do it too, only to find it's a removed function. Damn shame.
> 
> I've tried with Connect Plus and it's a really cool app, but for some reason it doesn't seem to show the chipset even for mine to be able to confirm the type? Really wish I could downgrade it to an older FW though if you end up figuring it out.

All Xtreme2 GM are qcc chips. I've tried almost everything I know. I even went to the extent of creating a fake company to register in the Qualcomm website and download all the official qcc 5xxx chip tools. There are 2 main issues. Firstly @pembem22 's app only supports .dfu files and not .bin (and for that to work a bin to dfu converter is needed and I haven't found any). The second issue is that the Xtreme 2 when I connect it to my pc it shows up as Xtreme 2 keyboard and/or Qualcomm usb hub. Entering dfu mode(play and volume- for 10s) wont change anything. So that's where I'm stuck. If you can figure out smthng let me know.

**Comment by pembem22** [comment] 2022-12-02 18:32
I don't have any QCC speakers around for testing and haven't had a chance to reverse engineer the process of flashing QCC firmware. You can try flashing .bin file using v1.1.3, but there's no guarantee it will work. Contributions are welcome if you can figure that out.

> I've tried with Connect Plus and it's a really cool app, but for some reason it doesn't seem to show the chipset even for mine to be able to confirm the type?
You have to use the [latest version](https://github.com/pembem22/connect-plus/releases/tag/v1.2.0-pre01) of the app to see chipset. 

Duplicate of #58

**Comment by pembem22** [comment] 2022-12-02 18:33
Duplicate of #58

**Closed by pembem22** 2022-12-02 18:32 UTC

**Comment by Tech-187** [comment] 2022-12-16 18:38
So the thing is, every Xtreme 2 that is still being made has a QCC chipset and is updated to the latest version by default.
Most people here really want to downgrade their Xtreme 2's similarly to how you made the Charge 3 downgrade possible.

It would be nice if you do figure it out at some point as the Xtreme 2 is literally one of the more safe speakers to test lfm on **as far as I know**
