### ISSUE TITLE
JBL Charge 5 Stuck Connecting

### ISSUE THREAD

**Issue by JBLmonkey** [pembem22/connect-plus#82] opened 2024-04-26 01:55 UTC
When trying to use the app, it stays on "Connecting to JBL Charge 5" forever. Tried factory resetting the speaker and it didn't work either

**Comment by pembem22** [comment] 2024-04-26 10:43
Duplicate of #64

**Comment by pembem22** [comment] 2024-04-26 10:43
Connecting to Charge 5 is not supported at the moment.

**Closed by pembem22** 2024-04-26 10:43 UTC
