### ISSUE TITLE
Updated APK

### ISSUE THREAD

**Issue by charbelhelou** [pembem22/connect-plus#79] opened 2024-01-04 17:19 UTC
Hello, I am trying to fix a JBL Boombox 3 speaker I just got. I updated to the latest firmware on their official app and there is no audio coming out anymore after pairing. I did a lot of research and stumbled onto this repo.

I have a question though. How is everyone using the updated code of this project? I couldn't find any APK in the Releases section other than the one uploaded a year ago (which doesn't support Boombox 3 yet). Do we have to download the source code and try to run it ourself? Or are you going to release a new APK soon?

Thanks :)

**Comment by pembem22** [comment] 2024-01-04 18:40
Hi, I'm trying to fix the remaining bugs and plan to release a new version after it's done. However, there will still be no support for Boombox 3 and newer speakers, as that requires supporting a different communication protocol, and I don't have a newer speaker to test and develop that. See issue #64.

**Comment by charbelhelou** [comment] 2024-01-04 18:42
Oh I see, I thought it will have support for Boombox 3. Do you have any idea if there is another way I can downgrade the firmware or attempt to fix it somehow? Any tips or a direction you advise I go to?

Much appreciated :)

**Comment by pembem22** [comment] 2024-01-04 19:30
None that I know of, unfortunately. You could try reverse engineering the protocol yourself if you have the experience.

**Comment by charbelhelou** [comment] 2024-01-04 19:50
I don't have any experience in that, but if you want, I have the speaker with me and I am a mobile dev, we could work together on trying to add it (of course if you like this idea)

**Comment by pembem22** [comment] 2024-01-22 11:00
Thanks for the offer, I might consider this in the future.

**Comment by pembem22** [comment] 2024-01-22 11:00
Duplicate of #64.

**Comment by pembem22** [comment] 2024-01-22 11:01
Duplicate of #64

**Closed by pembem22** 2024-01-22 11:01 UTC

**Comment by Randys0496** [comment] 2025-01-18 02:43
tengo el mismo problema con mi bb3 . se a encontrado una solucion
